# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KinPredUiv0.8.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(312, 727)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.inputheader = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inputheader.setFont(font)
        self.inputheader.setObjectName("inputheader")
        self.gridLayout.addWidget(self.inputheader, 0, 0, 1, 2)
        self.userinput = QtWidgets.QLineEdit(Form)
        self.userinput.setObjectName("userinput")
        self.gridLayout.addWidget(self.userinput, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.clearinput = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clearinput.setFont(font)
        self.clearinput.setObjectName("clearinput")
        self.gridLayout.addWidget(self.clearinput, 3, 0, 1, 1)
        self.seqsubmit = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.seqsubmit.setFont(font)
        self.seqsubmit.setObjectName("seqsubmit")
        self.gridLayout.addWidget(self.seqsubmit, 3, 1, 1, 1)
        self.outputtable = QtWidgets.QTableWidget(Form)
        self.outputtable.setObjectName("outputtable")
        self.outputtable.setColumnCount(2)
        self.outputtable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.outputtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.outputtable.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.outputtable, 4, 0, 1, 2)
        self.clearoutput = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clearoutput.setFont(font)
        self.clearoutput.setObjectName("clearoutput")
        self.gridLayout.addWidget(self.clearoutput, 5, 0, 1, 1)
        self.browse = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.gridLayout.addWidget(self.browse, 5, 1, 1, 1)
        self.filename = QtWidgets.QLineEdit(Form)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 6, 0, 1, 2)
        self.exportoutput = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exportoutput.setFont(font)
        self.exportoutput.setObjectName("exportoutput")
        self.gridLayout.addWidget(self.exportoutput, 7, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inputheader.setText(_translate("Form", "Input Centered 13 Peptide Sequence:"))
        self.label.setText(_translate("Form", "Centralized Amino Acid:"))
        self.radioButton.setText(_translate("Form", "Y"))
        self.radioButton_2.setText(_translate("Form", "S/T"))
        self.clearinput.setText(_translate("Form", "Clear Sequence"))
        self.seqsubmit.setText(_translate("Form", "Submit Sequence"))
        item = self.outputtable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Kinase"))
        item = self.outputtable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Dot Product"))
        self.clearoutput.setText(_translate("Form", "Clear Results"))
        self.browse.setText(_translate("Form", "Set Folder"))
        self.exportoutput.setText(_translate("Form", "Export Data "))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
